name: Publish to Registry
on:    
  push:
    tags:
      - '*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: clabroche/docker-registry/mine
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: docker.pkg.github.com
        buildargs: --build-arg VUE_APP_HOST=${{secrets.VUE_APP_HOST}} --build-arg VUE_APP_SOCKET=${{secrets.VUE_APP_SOCKET}}
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
